default:
  image: 
    name: hashicorp/terraform
    entrypoint: [""]
  timeout: 15 minutes
  cache:
    - key: $CI_PIPELINE_ID-terraform-cache
      paths:
        - .terraform/
        - .terraform.lock.hcl

variables:
  ANSIBLE_HOST_KEY_CHECKING: 'false'
  ANSIBLE_FORCE_COLOR: 'true'
  TF_DIR: ${CI_PROJECT_DIR}
  STATEFILE_NAME: "terraform.tfstate"   
  ADDRESS: "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/terraform/state/${STATEFILE_NAME}"

stages:
  - format
  - init  
  - validate
  - security-scan
  - apply
  - configure
  - destroy

format:
  stage: format
  script:
    - terraform fmt
  cache: []
  allow_failure: true

download_provider:
  stage: init
  script:
    - terraform init
      -backend-config="address=${ADDRESS}"
      -backend-config="lock_address=${ADDRESS}/lock"
      -backend-config="unlock_address=${ADDRESS}/lock"
      -backend-config="username=${GITLAB_USERNAME}" 
      -backend-config="password=${GITLAB_ACCESS_TOKEN}"
      -backend-config="lock_method=POST" 
      -backend-config="unlock_method=DELETE"
      -backend-config="retry_wait_min=5" 

validate:
  stage: validate
  script:
    - terraform validate

scan:
  image: 
    name: aquasec/tfsec-ci
    entrypoint: [""]
  stage: security-scan
  script:
    - tfsec .

apply_configuration:
  stage: apply
  script:
    - export AWS_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - terraform apply -auto-approve
  artifacts:
    name: "$CI_JOB_NAME-${CI_JOB_ID}"
    paths:
      - ./hosts
    expire_in: 1 day

ansible:
  stage: configure
  image: 
    name: alpinelinux/ansible:latest
    entrypoint: [""]
  script:
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ansible-playbook -i hosts install-apache.yml
  cache: []

destroy_infra:
  when: manual
  stage: destroy
  script:
    - export AWS_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - terraform destroy -auto-approve
