default:
  image: 
    name: hashicorp/terraform
    entrypoint: [""]
  timeout: 15 minutes
stages:
  - format
  - init
  - validate
  - apply
  - destroy
format:
  stage: format
  image: actions/ssh-keygen
  entrypoint: [""]
  script:
    - ssh-keygen -t rsa -f ./gitlab -q -P ""

# format:
#   stage: format
#   script:
#     - terraform fmt

# download_provider:
#   stage: init
#   script:
#     - terraform init

# apply_configuration:
#   stage: apply
#   script:
#     - terraform apply -auto-approve
#   artifacts:
#     paths:
#       - hosts

# destroy_infra:
#   when: never
#   stage: destroy
#   script:
#     - terraform destroy -auto-approve