default:
  image: 
    name: hashicorp/terraform
    entrypoint: [""]
stages:
  - format
  - init
  - validate
  - plan
  - apply
  - destroy

format:
  stage: format
  script:
    - terraform fmt

download_provider:
  stage: init
  script:
    - terraform init